window.FANTASY_PLAYERS = [
  {
    name: "Oihan Sancet",
    team: "Athletic",
    nationalTeam: "Espana",
    position: "MC",
    price: 12300000,
    starter: 86,
    form: 78,
    asScore: 84,
    sofascore: 76,
    stats: 74,
    valueTrend: 6,
    risk: "medium",
    riskReasons: ["Puede rotar si llega con carga fisica", "Perfil con cierta dependencia de gol"],
    sources: ["FutbolFantasy", "Jornada Perfecta", "Transfermarkt"],
    note: "Mediapunta diferencial, buen techo en picas y puntos mixtos cuando Athletic domina.",
    competitionProfiles: {
      worldcup: {
        team: "Espana",
        starter: 42,
        form: 76,
        asScore: 72,
        sofascore: 70,
        stats: 68,
        valueTrend: 1,
        risk: "high",
        riskReasons: ["Rol menos consolidado con Espana", "Competencia alta en la mediapunta"],
        sources: ["Contexto seleccion", "Predicted11", "FutbolFantasy"],
        note: "En Mundial baja la recomendacion: puede entrar en convocatoria, pero no parte como titular claro."
      }
    }
  },
  {
    name: "Ante Budimir",
    team: "Osasuna",
    nationalTeam: "Croacia",
    position: "DL",
    price: 9800000,
    starter: 91,
    form: 82,
    asScore: 78,
    sofascore: 80,
    stats: 86,
    valueTrend: 4,
    risk: "low",
    riskReasons: ["Dependencia del gol", "Menor valor si el rival concede poco por arriba"],
    sources: ["FutbolFantasy", "Predicted11", "Jornada Perfecta"],
    note: "Delantero de minutos muy estables y con valor alto en sistemas estadisticos por remate y penaltis.",
    competitionProfiles: {
      worldcup: {
        team: "Croacia",
        starter: 68,
        form: 80,
        asScore: 72,
        sofascore: 75,
        stats: 80,
        valueTrend: 3,
        risk: "medium",
        riskReasons: ["Puede alternar titularidad segun rival", "Dependencia del gol en pocos partidos"],
        sources: ["Contexto seleccion", "Predicted11", "Transfermarkt"],
        note: "Con Croacia mantiene valor por perfil de nueve, aunque el rol no es tan blindado como en Osasuna."
      }
    }
  },
  {
    name: "Pepelu",
    team: "Valencia",
    nationalTeam: "Espana",
    position: "MC",
    price: 5900000,
    starter: 88,
    form: 70,
    asScore: 67,
    sofascore: 72,
    stats: 79,
    valueTrend: 3,
    risk: "low",
    riskReasons: ["Techo moderado en picas si el partido es plano"],
    sources: ["FutbolFantasy", "Transfermarkt"],
    note: "Centro de gravedad del Valencia, barato para su volumen y especialmente util en estadisticas.",
    competitionProfiles: {
      worldcup: {
        team: "Espana",
        starter: 14,
        form: 66,
        asScore: 56,
        sofascore: 60,
        stats: 63,
        valueTrend: -3,
        risk: "high",
        riskReasons: ["No tiene rol estable en Espana", "Riesgo de no entrar o jugar minutos residuales"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "En formato selecciones pierde mucho atractivo por falta de rol claro con Espana."
      }
    }
  },
  {
    name: "Take Kubo",
    team: "Real Sociedad",
    nationalTeam: "Japon",
    position: "DL",
    price: 15100000,
    starter: 82,
    form: 74,
    asScore: 82,
    sofascore: 78,
    stats: 76,
    valueTrend: 2,
    risk: "medium",
    riskReasons: ["Precio alto", "Puede sufrir ante rivales encerrados"],
    sources: ["FutbolFantasy", "Predicted11", "Jornada Perfecta"],
    note: "Jugador de techo alto y buena lectura en picas, aunque exige pagar prima.",
    competitionProfiles: {
      worldcup: {
        team: "Japon",
        starter: 88,
        form: 78,
        asScore: 82,
        sofascore: 82,
        stats: 84,
        valueTrend: 5,
        risk: "low",
        riskReasons: ["Mayor responsabilidad ofensiva", "Calendario corto con techo alto y varianza"],
        sources: ["Contexto seleccion", "Predicted11", "Transfermarkt"],
        note: "En Japon gana peso: rol principal, balon parado y mucha participacion ofensiva."
      }
    }
  },
  {
    name: "Dani Vivian",
    team: "Athletic",
    nationalTeam: "Espana",
    position: "DF",
    price: 6200000,
    starter: 93,
    form: 73,
    asScore: 72,
    sofascore: 75,
    stats: 76,
    valueTrend: 5,
    risk: "low",
    riskReasons: ["Menor techo ofensivo"],
    sources: ["FutbolFantasy", "Predicted11"],
    note: "Defensa fiable por minutos y equipo competitivo, buen equilibrio para completar plantilla.",
    competitionProfiles: {
      worldcup: {
        team: "Espana",
        starter: 34,
        form: 72,
        asScore: 62,
        sofascore: 66,
        stats: 68,
        valueTrend: 0,
        risk: "high",
        riskReasons: ["Competencia fuerte en centrales", "Titularidad condicionada por bajas"],
        sources: ["Contexto seleccion", "Predicted11"],
        note: "Buen defensa de club, pero en Espana su valor depende de convocatoria y rotaciones."
      }
    }
  },
  {
    name: "Raphinha",
    team: "Barcelona",
    nationalTeam: "Brasil",
    position: "DL",
    price: 18400000,
    starter: 76,
    form: 86,
    asScore: 83,
    sofascore: 84,
    stats: 88,
    valueTrend: 7,
    risk: "medium",
    riskReasons: ["Competencia alta en ataque", "Calendario con posible rotacion"],
    sources: ["FutbolFantasy", "Predicted11", "Transfermarkt"],
    note: "Produccion elite cuando es titular; compra agresiva solo si el mercado esta corto de delanteros.",
    competitionProfiles: {
      worldcup: {
        team: "Brasil",
        starter: 74,
        form: 84,
        asScore: 80,
        sofascore: 82,
        stats: 86,
        valueTrend: 4,
        risk: "medium",
        riskReasons: ["Competencia alta en bandas", "Puede alternar titularidad segun plan de partido"],
        sources: ["Contexto seleccion", "Predicted11", "Transfermarkt"],
        note: "Con Brasil conserva techo alto, pero la competencia de ataque aumenta el riesgo."
      }
    }
  },
  {
    name: "Lucas Boye",
    team: "Granada",
    nationalTeam: "Argentina",
    position: "DL",
    price: 4200000,
    starter: 71,
    form: 62,
    asScore: 60,
    sofascore: 65,
    stats: 72,
    valueTrend: 8,
    risk: "high",
    riskReasons: ["Equipo irregular", "Riesgo de amarillas y baja eficiencia"],
    sources: ["Jornada Perfecta", "Transfermarkt"],
    note: "Puede ser una apuesta de valor si necesitas delantero barato, pero no conviene sobrepujar.",
    competitionProfiles: {
      worldcup: {
        team: "Argentina",
        starter: 8,
        form: 58,
        asScore: 50,
        sofascore: 55,
        stats: 58,
        valueTrend: -4,
        risk: "high",
        riskReasons: ["Rol muy alejado de la titularidad", "Riesgo alto de no tener minutos"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "En Mundial queda como apuesta muy especulativa por falta de rol con Argentina."
      }
    }
  },
  {
    name: "Joan Garcia",
    team: "Espanyol",
    nationalTeam: "Espana",
    position: "POR",
    price: 7300000,
    starter: 95,
    form: 80,
    asScore: 75,
    sofascore: 83,
    stats: 84,
    valueTrend: 5,
    risk: "low",
    riskReasons: ["Los porteros dependen mucho del guion de partido"],
    sources: ["FutbolFantasy", "Predicted11", "Transfermarkt"],
    note: "Portero de paradas, muy solido en SofaScore y estadisticas.",
    competitionProfiles: {
      worldcup: {
        team: "Espana",
        starter: 18,
        form: 78,
        asScore: 58,
        sofascore: 65,
        stats: 66,
        valueTrend: -2,
        risk: "high",
        riskReasons: ["Porteria de Espana muy competitiva", "Puede ir convocado sin ser titular"],
        sources: ["Contexto seleccion", "Predicted11"],
        note: "Como portero de seleccion su recomendacion cae si no es titular confirmado."
      }
    }
  },
  {
    name: "Isco",
    team: "Betis",
    nationalTeam: "Espana",
    position: "MC",
    price: 16700000,
    starter: 84,
    form: 88,
    asScore: 92,
    sofascore: 86,
    stats: 82,
    valueTrend: 5,
    risk: "medium",
    riskReasons: ["Gestion fisica", "Precio premium"],
    sources: ["FutbolFantasy", "Jornada Perfecta", "Transfermarkt"],
    note: "Perfil perfecto para picas y media; justifica prima si tu liga premia regularidad creativa.",
    competitionProfiles: {
      worldcup: {
        team: "Espana",
        starter: 28,
        form: 84,
        asScore: 74,
        sofascore: 72,
        stats: 68,
        valueTrend: -1,
        risk: "high",
        riskReasons: ["Rol internacional menos previsible", "Precio premium para una titularidad dudosa"],
        sources: ["Contexto seleccion", "Jornada Perfecta", "Transfermarkt"],
        note: "En clubes es perfil premium; en Mundial solo compensa si hay senales claras de rol importante."
      }
    }
  },
  {
    name: "Javi Guerra",
    team: "Valencia",
    nationalTeam: "Espana",
    position: "MC",
    price: 7100000,
    starter: 78,
    form: 69,
    asScore: 68,
    sofascore: 70,
    stats: 72,
    valueTrend: 9,
    risk: "medium",
    riskReasons: ["Minutaje menos blindado", "Rendimiento variable"],
    sources: ["FutbolFantasy", "Jornada Perfecta"],
    note: "Interesante como inversion por potencial de subida, no como pieza segura.",
    competitionProfiles: {
      worldcup: {
        team: "Espana",
        starter: 12,
        form: 66,
        asScore: 54,
        sofascore: 58,
        stats: 61,
        valueTrend: -4,
        risk: "high",
        riskReasons: ["Rol de seleccion poco consolidado", "Mas apuesta de futuro que fichaje inmediato"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "En Mundial pierde prioridad por incertidumbre de convocatoria y minutos."
      }
    }
  },
  {
    name: "Roozbeh Cheshmi",
    team: "Esteghlal FC",
    nationalTeam: "Iran",
    position: "MC",
    price: 370000,
    starter: 78,
    form: 64,
    asScore: 61,
    sofascore: 66,
    stats: 64,
    valueTrend: 2,
    risk: "medium",
    riskReasons: ["Perfil de rotacion", "Aporta mas por contexto que por techo fantasy"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Perfil util como fondo de armario si necesitas minutos en competicion de selecciones.",
    competitionProfiles: {
      worldcup: {
        team: "Iran",
        starter: 74,
        form: 62,
        asScore: 59,
        sofascore: 64,
        stats: 62,
        valueTrend: 1,
        risk: "medium",
        riskReasons: ["Titularidad probable pero no blindada", "Techo fantasy limitado"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "En Mundial suma por rol y precio, mas que por explosividad."
      }
    }
  },
  {
    name: "Jassem Abdulsallam",
    team: "Qatar SC",
    nationalTeam: "Qatar",
    position: "MC",
    price: 190000,
    starter: 70,
    form: 58,
    asScore: 56,
    sofascore: 60,
    stats: 58,
    valueTrend: 1,
    risk: "medium",
    riskReasons: ["Rol corto de seguridad", "Produccion fantasy modesta"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Apuesta economica muy situacional.",
    competitionProfiles: {
      worldcup: {
        team: "Qatar",
        starter: 72,
        form: 57,
        asScore: 56,
        sofascore: 60,
        stats: 57,
        valueTrend: 1,
        risk: "medium",
        riskReasons: ["Puede alternar minutos", "Valoracion dependiente del contexto"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Sirve como parche barato si necesitas profundidad."
      }
    }
  },
  {
    name: "Rafael Leao",
    team: "Milan",
    nationalTeam: "Portugal",
    position: "DL",
    price: 13720000,
    starter: 82,
    form: 84,
    asScore: 78,
    sofascore: 82,
    stats: 83,
    valueTrend: 5,
    risk: "medium",
    riskReasons: ["Competencia ofensiva fuerte", "Precio premium"],
    sources: ["FutbolFantasy", "Transfermarkt"],
    note: "Delantero de techo alto cuando el contexto apunta a titularidad real.",
    competitionProfiles: {
      worldcup: {
        team: "Portugal",
        starter: 76,
        form: 81,
        asScore: 74,
        sofascore: 79,
        stats: 80,
        valueTrend: 3,
        risk: "medium",
        riskReasons: ["Competencia de nivel top", "Puede alternar once y minutos"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Muy potente en Mundial si las fuentes confirman rol de titular."
      }
    }
  },
  {
    name: "Anthony Elanga",
    team: "Nottingham Forest",
    nationalTeam: "Suecia",
    position: "DL",
    price: 6930000,
    starter: 77,
    form: 73,
    asScore: 69,
    sofascore: 72,
    stats: 75,
    valueTrend: 4,
    risk: "medium",
    riskReasons: ["Depende de plan de partido", "Rendimiento irregular por tramos"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Extremo vertical interesante si su titularidad se sostiene.",
    competitionProfiles: {
      worldcup: {
        team: "Suecia",
        starter: 75,
        form: 71,
        asScore: 68,
        sofascore: 71,
        stats: 74,
        valueTrend: 3,
        risk: "medium",
        riskReasons: ["No siempre fija 90 minutos", "Depende de encaje tactico"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Buen perfil si necesitas un delantero de ritmo con coste medio."
      }
    }
  },
  {
    name: "Thiago Almada",
    team: "Atletico de Madrid",
    nationalTeam: "Argentina",
    position: "MC",
    price: 6080000,
    starter: 71,
    form: 76,
    asScore: 70,
    sofascore: 74,
    stats: 77,
    valueTrend: 4,
    risk: "medium",
    riskReasons: ["Mucho talento, menos certeza de minutos", "Competencia muy alta"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Apuesta interesante por calidad, pero muy dependiente del once.",
    competitionProfiles: {
      worldcup: {
        team: "Argentina",
        starter: 54,
        form: 73,
        asScore: 66,
        sofascore: 71,
        stats: 73,
        valueTrend: 1,
        risk: "high",
        riskReasons: ["Rol internacional cambiante", "Competencia extrema en Argentina"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Solo recomendable si las fuentes lo acercan claramente al once."
      }
    }
  },
  {
    name: "Julian Quinones",
    team: "Club America",
    nationalTeam: "Mexico",
    position: "DL",
    price: 4800000,
    starter: 79,
    form: 72,
    asScore: 68,
    sofascore: 71,
    stats: 73,
    valueTrend: 4,
    risk: "medium",
    riskReasons: ["Puede alternar perfiles en ataque", "Necesita continuidad de minutos"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Delantero interesante de precio medio si sostiene titularidad.",
    competitionProfiles: {
      worldcup: {
        team: "Mexico",
        starter: 76,
        form: 70,
        asScore: 67,
        sofascore: 70,
        stats: 72,
        valueTrend: 3,
        risk: "medium",
        riskReasons: ["Puede perder peso segun el rival", "No siempre completa partidos"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Buena pieza si buscas delantero util sin pagar un premium."
      }
    }
  },
  {
    name: "Matias Fernandez-Pardo",
    team: "Lille",
    nationalTeam: "Belgica",
    position: "DL",
    price: 4640000,
    starter: 63,
    form: 65,
    asScore: 61,
    sofascore: 66,
    stats: 67,
    valueTrend: 3,
    risk: "high",
    riskReasons: ["Rol poco consolidado", "Mucho desarrollo por delante"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Apuesta de futuro, no perfil seguro a corto plazo.",
    competitionProfiles: {
      worldcup: {
        team: "Belgica",
        starter: 42,
        form: 63,
        asScore: 58,
        sofascore: 64,
        stats: 65,
        valueTrend: 1,
        risk: "high",
        riskReasons: ["Muy lejos del rol fijo", "Compite con perfiles mas asentados"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Solo para apuestas muy especulativas."
      }
    }
  },
  {
    name: "Gael Kakuta",
    team: "Amiens",
    nationalTeam: "RD Congo",
    position: "MC",
    price: 840000,
    starter: 64,
    form: 60,
    asScore: 59,
    sofascore: 63,
    stats: 61,
    valueTrend: 0,
    risk: "high",
    riskReasons: ["Veterano con carga de minutos incierta", "Techo limitado"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Nombre reconocible, pero solo recomendable como parche barato.",
    competitionProfiles: {
      worldcup: {
        team: "RD Congo",
        starter: 58,
        form: 59,
        asScore: 57,
        sofascore: 61,
        stats: 60,
        valueTrend: 0,
        risk: "high",
        riskReasons: ["Titularidad discutible", "Poca continuidad reciente"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Solo compensa por precio si necesitas completar plantilla."
      }
    }
  },
  {
    name: "Sebastian Tounekti",
    team: "Haugesund",
    nationalTeam: "Tunez",
    position: "DL",
    price: 550000,
    starter: 60,
    form: 61,
    asScore: 58,
    sofascore: 62,
    stats: 63,
    valueTrend: 1,
    risk: "high",
    riskReasons: ["Rol menor", "Apuesta de minutos residuales"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Delantero muy barato, mas fondo de armario que recomendacion real.",
    competitionProfiles: {
      worldcup: {
        team: "Tunez",
        starter: 48,
        form: 60,
        asScore: 57,
        sofascore: 61,
        stats: 62,
        valueTrend: 1,
        risk: "high",
        riskReasons: ["Lejos de la titularidad fija", "Valor fantasy bajo"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "Pieza residual, solo para presupuestos muy cortos."
      }
    }
  },
  {
    name: "Jeremy Arevalo",
    team: "Sporting Gijon",
    nationalTeam: "Ecuador",
    position: "DL",
    price: 260000,
    starter: 52,
    form: 55,
    asScore: 53,
    sofascore: 57,
    stats: 56,
    valueTrend: 1,
    risk: "high",
    riskReasons: ["Muy poca certeza de rol", "Perfil de futuro"],
    sources: ["Contexto seleccion", "Transfermarkt"],
    note: "Apuesta extremadamente especulativa.",
    competitionProfiles: {
      worldcup: {
        team: "Ecuador",
        starter: 36,
        form: 54,
        asScore: 52,
        sofascore: 56,
        stats: 55,
        valueTrend: 1,
        risk: "high",
        riskReasons: ["No tiene rol consolidado", "Minutos muy inciertos"],
        sources: ["Contexto seleccion", "Transfermarkt"],
        note: "No deberia priorizarse salvo liga muy profunda."
      }
    }
  }
];

window.TEAM_ALIASES = {
  "athletic": "Athletic",
  "athletic club": "Athletic",
  "osasuna": "Osasuna",
  "valencia": "Valencia",
  "real sociedad": "Real Sociedad",
  "barcelona": "Barcelona",
  "barca": "Barcelona",
  "betis": "Betis",
  "granada": "Granada",
  "espanyol": "Espanyol",
  "mallorca": "Mallorca",
  "villarreal": "Villarreal",
  "girona": "Girona",
  "atletico": "Atletico",
  "atletico madrid": "Atletico",
  "real madrid": "Real Madrid",
  "sevilla": "Sevilla",
  "getafe": "Getafe",
  "rayo": "Rayo",
  "celta": "Celta",
  "alaves": "Alaves",
  "real oviedo": "Oviedo",
  "oviedo": "Oviedo",
  "levante": "Levante",
  "elche": "Elche"
};

window.NATIONAL_TEAM_ALIASES = {
  "espana": "Espana",
  "españa": "Espana",
  "spain": "Espana",
  "croacia": "Croacia",
  "croatia": "Croacia",
  "japon": "Japon",
  "japan": "Japon",
  "brasil": "Brasil",
  "brazil": "Brasil",
  "argentina": "Argentina",
  "francia": "Francia",
  "france": "Francia",
  "alemania": "Alemania",
  "germany": "Alemania",
  "inglaterra": "Inglaterra",
  "england": "Inglaterra",
  "portugal": "Portugal",
  "italia": "Italia",
  "italy": "Italia",
  "paises bajos": "Paises Bajos",
  "holanda": "Paises Bajos",
  "netherlands": "Paises Bajos",
  "uruguay": "Uruguay",
  "belgica": "Belgica",
  "belgium": "Belgica",
  "marruecos": "Marruecos",
  "morocco": "Marruecos",
  "noruega": "Noruega",
  "norway": "Noruega",
  "bosnia": "Bosnia y Herzegovina",
  "bosnia and herzegovina": "Bosnia y Herzegovina",
  "bosnia & herzegovina": "Bosnia y Herzegovina",
  "haiti": "Haiti",
  "irak": "Irak",
  "iraq": "Irak",
  "colombia": "Colombia",
  "uzbekistan": "Uzbekistan",
  "croatia": "Croacia",
  "escocia": "Escocia",
  "scotland": "Escocia",
  "ecuador": "Ecuador",
  "iran": "Iran",
  "mexico": "Mexico",
  "qatar": "Qatar",
  "estados unidos": "Estados Unidos",
  "united states": "Estados Unidos",
  "united states of america": "Estados Unidos",
  "usa": "Estados Unidos",
  "usmnt": "Estados Unidos",
  "senegal": "Senegal",
  "australia": "Australia",
  "argelia": "Argelia",
  "algeria": "Argelia",
  "suiza": "Suiza",
  "switzerland": "Suiza",
  "austria": "Austria",
  "ghana": "Ghana",
  "panama": "Panama",
  "paraguay": "Paraguay",
  "canada": "Canada",
  "egipto": "Egipto",
  "egypt": "Egipto",
  "cabo verde": "Cabo Verde",
  "cape verde": "Cabo Verde",
  "costa de marfil": "Costa de Marfil",
  "ivory coast": "Costa de Marfil",
  "cote d ivoire": "Costa de Marfil",
  "jordania": "Jordania",
  "jordan": "Jordania",
  "nueva zelanda": "Nueva Zelanda",
  "new zealand": "Nueva Zelanda",
  "arabia saudi": "Arabia Saudi",
  "arabia saudita": "Arabia Saudi",
  "saudi arabia": "Arabia Saudi",
  "sudafrica": "Sudafrica",
  "south africa": "Sudafrica",
  "turquia": "Turquia",
  "turkey": "Turquia",
  "turkiye": "Turquia",
  "chequia": "Chequia",
  "czechia": "Chequia",
  "czech republic": "Chequia",
  "curazao": "Curazao",
  "curacao": "Curazao",
  "suecia": "Suecia",
  "sweden": "Suecia",
  "republica democratica del congo": "RD Congo",
  "dr congo": "RD Congo",
  "congo dr": "RD Congo",
  "congo rdc": "RD Congo",
  "congo (rdc)": "RD Congo",
  "rd congo": "RD Congo",
  "tunez": "Tunez",
  "tunisia": "Tunez",
  "corea del sur": "Corea del Sur",
  "south korea": "Corea del Sur",
  "korea republic": "Corea del Sur"
};
