<?php
declare(strict_types=1);
require_once __DIR__ . '/market-advisor-sources.php';
/* Private, outbound-only PC relay. This file never invokes an LLM or operations. */
function ma_fail(string $code, int $status = 400): void { send_json($status, ['error' => $code]); }
function ma_text($v, int $max = 240): string { if (!is_scalar($v) && $v !== null) ma_fail('invalid_schema'); return substr(preg_replace('/[\x00-\x1f<>]/', '', (string)$v), 0, $max); }
function ma_money($v): ?int { return is_int($v) && $v >= 0 && $v <= 1000000000000 ? $v : null; }
function ma_allowed(array $u, string $dbDir): bool {
    $ids = array_filter(explode(',', (string)getenv('FMS_MARKET_AGENT_ALLOWED_USERS')));
    $file = $dbDir . '/market-agent-allowed-users.json';
    if (is_file($file)) { $allowed = json_decode((string)file_get_contents($file), true); $ids = (array)($allowed['userIds'] ?? []); }
    return in_array((string)$u['id'], $ids, true);
}
function ma_context(array $c, array $user): array {
    if (!in_array($c['profile'] ?? '', ['prudent','balanced','aggressive'], true) || !in_array($c['horizonRounds'] ?? 0, [1,3], true)) ma_fail('invalid_schema');
    if (empty($c['leagueId']) || !is_array($c['market'] ?? null) || !is_array($c['squad'] ?? null) || !is_array($c['evidence'] ?? null) || !is_array($c['rivals'] ?? [])) ma_fail('invalid_schema');
    if (!empty($c['squad'])) auth_require_permission($user, 'team');
    if (!empty($c['rivals']) || !empty($c['myStanding'])) auth_require_permission($user, 'league');
    if (count($c['market']) > 25 || count($c['squad']) > 40 || count($c['evidence']) > 260 || count($c['rivals'] ?? []) > 50) ma_fail('context_too_large');
    $out=[]; foreach (['leagueId','competition','scoring','asOf'] as $k) $out[$k]=ma_text($c[$k] ?? '',64);
    $out['profile']=$c['profile'];$out['horizonRounds']=$c['horizonRounds'];
    $f=(array)($c['finance'] ?? []); $out['finance']=['updatedAt'=>ma_text($f['updatedAt'] ?? '',40)];
    foreach(['balance','maximumBid','committedBids','availableBudget'] as $k) $out['finance'][$k]=($k==='balance' && is_int($f[$k]??null) && abs($f[$k])<=1000000000000)?$f[$k]:ma_money($f[$k] ?? null);
    $ids=[];
    foreach(['market','squad'] as $kind){$out[$kind]=[];foreach($c[$kind] as $p){if(!is_array($p))ma_fail('invalid_schema');$id=ma_text($p['id'] ?? '',64);if(!$id || isset($ids[$id]))ma_fail('invalid_player');$ids[$id]=true;$row=['id'=>$id];foreach(['name','team','position','reliability'] as $k)$row[$k]=ma_text($p[$k] ?? '',100);foreach(['price','points','rationalMax','recommendedBid','ownBid'] as $k)$row[$k]=($k==='points'&&is_int($p[$k]??null)&&abs($p[$k])<=1000000000)?$p[$k]:ma_money($p[$k] ?? null);$row['rationalMax']=$row['rationalMax'] ?? 0;$row['evidenceIds']=array_slice(array_map(fn($v)=>ma_text($v,80),(array)($p['evidenceIds'] ?? [])),0,8);$out[$kind][]=$row;}}
    $out['evidence']=[];$eids=[];foreach($c['evidence'] as $e){if(!is_array($e)||!in_array($e['type']??'',['news','health','form','fixture','finance','standing','roster'],true))ma_fail('invalid_evidence');$id=ma_text($e['id']??'',80);if(!$id||isset($eids[$id]))ma_fail('invalid_evidence');$eids[$id]=true;$row=['id'=>$id,'type'=>$e['type']];foreach(['playerId','source','publishedAt','fetchedAt','title','value','sourceHost','sourceKind','platform','recommendationScope','authorName','authorRole','authorVerification','parentId','commentId']as$k)$row[$k]=ma_text($e[$k]??'',$k==='value'?1000:240);if($row['playerId']&&!isset($ids[$row['playerId']]))ma_fail('invalid_evidence');if(isset($e['url'])&&is_string($e['url'])){$u=parse_url($e['url']);if(($u['scheme']??'')==='https'&&!isset($u['user'])&&!isset($u['pass']))$row['url']=substr($e['url'],0,1000);}$out['evidence'][]=$row;}
    foreach(array_merge($out['market'],$out['squad']) as $p)foreach($p['evidenceIds'] as $id)if(!isset($eids[$id]))ma_fail('invalid_evidence');
    $out['rivals']=[];foreach((array)($c['rivals']??[])as$i=>$r){$out['rivals'][]=['alias'=>'R'.($i+1),'rank'=>ma_money($r['rank']??null),'points'=>ma_money($r['points']??null),'summary'=>ma_text($r['summary']??'',500)];}
    $out['myStanding']=null;if(is_array($c['myStanding']??null)){$out['myStanding']=[];foreach(['rank','points','gapToLeader']as$k)$out['myStanding'][$k]=ma_money($c['myStanding'][$k]??null);}
    $out['coverage']=['market'=>count($out['market'])>0,'squad'=>count($out['squad'])>0,'rivalsLoaded'=>count($out['rivals']),'rivalsTotal'=>min(100,ma_money($c['coverage']['rivalsTotal']??0)??0),'warnings'=>array_slice(array_map(fn($v)=>ma_text($v),(array)($c['coverage']['warnings']??[])),0,8)];$out['coverage']['commentsUsed']=min(260,ma_money($c['coverage']['commentsUsed']??0)??0);$out['coverage']['sources']=null;if(is_array($c['coverage']['sources']??null)){$stats=[];foreach(['sourcePagesRequested','sourcePagesRead','articlePagesRead','threadsRead','repliesRead','verified','unverified','used']as$key)$stats[$key]=min(10000,ma_money($c['coverage']['sources'][$key]??0)??0);$out['coverage']['sources']=$stats;}return $out;
}
function ma_result(array $r,array $c): array {
    if(($r['schemaVersion']??0)!==1||!is_array($r['strategy']??null)||!is_array($r['actions']??null)||count($r['actions'])>12)ma_fail('invalid_output');
    $players=[];$market=[];$squad=[];foreach($c['market']as$p){$players[$p['id']]=$p;$market[$p['id']]=true;}foreach($c['squad']as$p){$players[$p['id']]=$p;$squad[$p['id']]=true;}$evidence=array_column($c['evidence'],'id');$seen=[];$sum=0;$actions=[];
    foreach($r['actions']as$a){if(!is_array($a))ma_fail('invalid_output');$type=$a['type']??'';$id=$a['playerId']??null;if(!is_string($id)&&$id!==null)ma_fail('invalid_output');$p=$players[$id]??null;if(!in_array($type,['buy','sell','hold','avoid','wait'],true)||!in_array($a['priority']??0,[1,2,3],true)||!in_array($a['confidence']??'',['low','medium','high'],true)||($type!=='wait'&&!$p)||($id&&isset($seen[$id])))ma_fail('invalid_output');if($id)$seen[$id]=true;if(($type==='buy'&&!isset($market[$id]))||(in_array($type,['sell','hold'],true)&&!isset($squad[$id])))ma_fail('invalid_output');if(!is_array($a['evidenceIds']??null))ma_fail('invalid_output');$refs=$a['evidenceIds'];foreach($refs as$ref)if(!is_string($ref)||!in_array($ref,$evidence,true))ma_fail('invalid_evidence');$amount=null;$max=null;if($type==='buy'){$amount=ma_money($a['amount']??null);$max=ma_money($a['maximumAmount']??null);$f=$c['finance'];$date=strtotime($f['updatedAt']);if(!$date||time()-$date>900||$date>time()+60||$amount===null||$max===null||($f['balance']===null||$f['balance']<0)||$f['availableBudget']===null||$f['maximumBid']===null||$amount>$max||$max>$p['rationalMax']||$max>$f['maximumBid'])ma_fail('invalid_budget');$sum+=max(0,$max-($p['ownBid']??0));}$actions[]=['type'=>$type,'playerId'=>$id,'priority'=>$a['priority'],'confidence'=>$a['confidence'],'reason'=>ma_text($a['reason']??'',500),'evidenceIds'=>array_slice($refs,0,8),'amount'=>$amount,'maximumAmount'=>$max,'prerequisites'=>array_slice(array_map(fn($v)=>ma_text($v),(array)($a['prerequisites']??[])),0,4)];}
    if($sum>($c['finance']['availableBudget']??0))ma_fail('invalid_budget');
    return ['schemaVersion'=>1,'mode'=>'ai','generatedAt'=>gmdate('c'),'strategy'=>['summary'=>ma_text($r['strategy']['summary']??'',700),'priorities'=>array_slice(array_map(fn($v)=>ma_text($v),(array)($r['strategy']['priorities']??[])),0,3)],'actions'=>$actions,'risks'=>array_slice(array_map(fn($v)=>ma_text($v),(array)($r['risks']??[])),0,6),'limitations'=>array_slice(array_map(fn($v)=>ma_text($v),(array)($r['limitations']??[])),0,6)];
}
function market_advisor_handle(string $route,string $method,string $usersPath,string $dbDir): void {
    if(strpos($route,'/market-advisor/')!==0)return;
    header('Cache-Control: no-store');
    $path=substr($route,15);$worker=strpos($path,'/worker/')===0;$user=null;
    if(!$worker){$user=auth_require_user($usersPath);auth_require_permission($user,'market');if(!ma_allowed($user,$dbDir)){if($path==='/status'&&$method==='GET')send_json(200,['enabled'=>false,'paired'=>false,'workerOnline'=>false]);ma_fail('advisor_not_enabled',403);}}
    $length=(int)($_SERVER['CONTENT_LENGTH']??0);if($length>131072)ma_fail('body_too_large',413);$raw=file_get_contents('php://input',false,null,0,131073);if(strlen($raw)>131072)ma_fail('body_too_large',413);$body=$raw===''?[]:json_decode($raw,true);if(!is_array($body))ma_fail('invalid_json');
    $dir=$dbDir.'/market-advisor';if(!is_dir($dir))mkdir($dir,0700,true);file_put_contents($dir.'/.htaccess',"Require all denied\nDeny from all\n");
    $fp=fopen($dir.'/relay.php.json','c+');if(!$fp||!flock($fp,LOCK_EX))ma_fail('relay_unavailable',503);$db=json_decode((string)stream_get_contents($fp),true)?:['accounts'=>[],'pairAttempts'=>[]];$now=time();
    $save=function()use(&$db,$fp){rewind($fp);ftruncate($fp,0);fwrite($fp,json_encode($db,JSON_UNESCAPED_UNICODE|JSON_INVALID_UTF8_SUBSTITUTE));fflush($fp);flock($fp,LOCK_UN);fclose($fp);};
    $reply=function($status,$data)use($save){$save();send_json($status,$data);};
    foreach($db['accounts']as&$a){if(($a['pairExpires']??0)<$now)unset($a['pairHash'],$a['pairExpires']);foreach($a['jobs']??[]as$id=>$j){if(($j['expires']??0)<$now){unset($a['jobs'][$id]);continue;}if(in_array($j['status'],['queued','running'],true)&&($j['deadline']??0)<$now){$a['jobs'][$id]=['id'=>$id,'requestId'=>$j['requestId'],'hash'=>$j['hash'],'status'=>'expired','expires'=>$now+900,'errorCode'=>'expired'];}}}unset($a);
    if($path==='/worker/pair'&&$method==='POST'){
        $ip=hash('sha256',(string)($_SERVER['REMOTE_ADDR']??''));$attempts=array_filter($db['pairAttempts'][$ip]??[],fn($t)=>$t>$now-600);if(count($attempts)>=12)$reply(429,['error'=>'pair_rate_limit']);$attempts[]=$now;$db['pairAttempts'][$ip]=$attempts;
        foreach($db['pairAttempts']as$key=>$times){$live=array_values(array_filter($times,fn($t)=>$t>$now-600));if(!$live)unset($db['pairAttempts'][$key]);else $db['pairAttempts'][$key]=$live;}if(count($db['pairAttempts'])>1000)$reply(429,['error'=>'pair_rate_limit']);$hash=hash('sha256',ma_text($body['pairCode']??'',100));foreach($db['accounts']as$accountId=>&$a){if(isset($a['pairHash'])&&hash_equals($a['pairHash'],$hash)&&$a['pairExpires']>=$now){$u=auth_find_user(auth_read_db($usersPath),(string)$accountId);if(!$u||!empty($u['blocked'])||!ma_allowed($u,$dbDir))$reply(403,['error'=>'account_disabled']);auth_require_permission($u,'market');$token=bin2hex(random_bytes(32));$a['workerHash']=hash('sha256',$token);$a['workerId']=bin2hex(random_bytes(16));$a['lastSeen']=$now;$a['jobs']=[];unset($a['pairHash'],$a['pairExpires']);$reply(200,['workerId'=>$a['workerId'],'workerToken'=>$token,'accountScope'=>$accountId]);}}unset($a);$reply(401,['error'=>'invalid_pair_code']);
    }
    if($worker){$header=(string)($_SERVER['HTTP_AUTHORIZATION']??'');if(!preg_match('/^Bearer ([a-f0-9]{64})$/',$header,$m))$reply(401,['error'=>'worker_auth']);$hash=hash('sha256',$m[1]);$accountId=null;foreach($db['accounts']as$id=>$a)if(isset($a['workerHash'])&&hash_equals($a['workerHash'],$hash)){$accountId=(string)$id;break;}if($accountId===null)$reply(401,['error'=>'worker_auth']);$user=auth_find_user(auth_read_db($usersPath),$accountId);if(!$user||!empty($user['blocked'])||!ma_allowed($user,$dbDir))$reply(403,['error'=>'account_disabled']);auth_require_permission($user,'market');}
    else $accountId=(string)$user['id'];
    if(!isset($db['accounts'][$accountId]))$db['accounts'][$accountId]=['jobs'=>[],'quota'=>[]];$a=&$db['accounts'][$accountId];
    if($path==='/status'&&$method==='GET')$reply(200,['enabled'=>true,'paired'=>isset($a['workerHash']),'workerOnline'=>isset($a['workerHash'])&&($a['lastSeen']??0)>$now-90,'lastSeenAt'=>isset($a['lastSeen'])?gmdate('c',$a['lastSeen']):null]);
    if($path==='/pair/start'&&$method==='POST'){if(($a['lastPair']??0)>$now-30)$reply(429,['error'=>'pair_cooldown']);$code=bin2hex(random_bytes(24));$a['pairHash']=hash('sha256',$code);$a['pairExpires']=$now+300;$a['lastPair']=$now;$reply(200,['pairCode'=>$code,'expiresAt'=>gmdate('c',$now+300)]);}
    if($path==='/pair/revoke'&&$method==='POST'){$a=['jobs'=>[],'quota'=>$a['quota']??[]];$reply(200,['revoked'=>true]);}
    if($path==='/news'&&$method==='POST'){
        if(($a['lastNews']??0)>$now-300)$reply(429,['error'=>'news_cooldown']);
        $players=$body['players']??[];if(!is_array($players)||count($players)>16)$reply(400,['error'=>'invalid_schema']);if(!function_exists('curl_multi_init'))$reply(503,['error'=>'news_unavailable']);$clean=[];
        foreach($players as$p){if(!is_array($p))$reply(400,['error'=>'invalid_schema']);$row=[];foreach(['key','name','team','clubTeam','nationalTeam','position']as$k)$row[$k]=ma_text($p[$k]??'',100);$row['biwengerPlayerId']=ma_money($p['biwengerPlayerId']??null)??0;$clean[]=$row;}
        $a['lastNews']=$now;$save();global $sourceHeaders;
        $known=$body['knownArticles']??[];if(!is_array($known)||count($known)>16)ma_fail('invalid_schema');
        try{send_json(200,market_advisor_sources($clean,($body['competition']??'')==='worldcup'?'worldcup':'club',$known));}catch(Throwable$e){ma_fail('news_unavailable',502);}
    }
    if($path==='/jobs'&&$method==='POST'){
        if(!isset($a['workerHash']))$reply(409,['error'=>'worker_not_paired']);if(($body['schemaVersion']??0)!==1||!preg_match('/^[a-zA-Z0-9-]{16,64}$/',(string)($body['requestId']??'')))$reply(400,['error'=>'invalid_schema']);$c=ma_context((array)($body['context']??[]),$user);$hash=hash('sha256',json_encode($c));foreach($a['jobs']as$j){if($j['requestId']===$body['requestId']){if($j['hash']!==$hash)$reply(409,['error'=>'request_conflict']);$reply(202,['jobId'=>$j['id'],'status'=>$j['status']]);}if(in_array($j['status'],['queued','running'],true))$reply(409,['error'=>'job_pending']);}
        $q=array_values(array_filter($a['quota']??[],fn($t)=>$t>$now-86400));if(count($q)>=20||count(array_filter($q,fn($t)=>$t>$now-3600))>=6||($q&&max($q)>$now-30))$reply(429,['error'=>'advisor_rate_limit']);$global=0;foreach($db['accounts']as$account)$global+=count($account['jobs']??[]);if($global>=50)$reply(503,['error'=>'relay_busy']);$q[]=$now;$a['quota']=$q;$id=bin2hex(random_bytes(16));$a['jobs'][$id]=['id'=>$id,'requestId'=>$body['requestId'],'hash'=>$hash,'status'=>'queued','context'=>$c,'deadline'=>$now+300,'expires'=>$now+600,'createdAt'=>gmdate('c')];$reply(202,['jobId'=>$id,'status'=>'queued','expiresAt'=>gmdate('c',$now+300),'snapshotHash'=>$hash]);
    }
    if($path==='/worker/claim'&&$method==='POST'){$a['lastSeen']=$now;foreach($a['jobs']as$id=>&$j){if($j['status']!=='queued')continue;ma_context($j['context'],$user);$context=$j['context'];unset($j['context']);$j['guards']=['market'=>$context['market'],'squad'=>$context['squad'],'requiresLeague'=>!empty($context['rivals'])||!empty($context['myStanding']),'finance'=>$context['finance'],'evidence'=>array_map(fn($e)=>['id'=>$e['id']],$context['evidence'])];foreach(['market','squad']as$kind)foreach($j['guards'][$kind]as&$p)unset($p['name'],$p['team'],$p['position'],$p['reliability'],$p['evidenceIds']);unset($p);$lease=bin2hex(random_bytes(24));$j['leaseHash']=hash('sha256',$lease);$j['workerId']=$a['workerId'];$j['status']='running';$j['deadline']=$now+180;$reply(200,['jobId'=>$id,'leaseId'=>$lease,'snapshotHash'=>$j['hash'],'context'=>$context,'expiresAt'=>gmdate('c',$j['deadline'])]);}unset($j);$reply(200,['job'=>null]);}
    if($path==='/worker/result'&&$method==='POST'){$id=(string)($body['jobId']??'');$j=$a['jobs'][$id]??null;if(!$j||$j['status']!=='running'||$j['workerId']!==$a['workerId']||!hash_equals($j['leaseHash'],hash('sha256',(string)($body['leaseId']??'')))||$j['deadline']<$now)$reply(409,['error'=>'invalid_lease']);if(!empty($j['guards']['squad']))auth_require_permission($user,'team');if(!empty($j['guards']['requiresLeague']))auth_require_permission($user,'league');$terminal=['id'=>$id,'requestId'=>$j['requestId'],'hash'=>$j['hash'],'expires'=>$now+900,'requiresTeam'=>!empty($j['guards']['squad']),'requiresLeague'=>!empty($j['guards']['requiresLeague'])];if(isset($body['result'])){$terminal['status']='completed';$terminal['result']=ma_result((array)$body['result'],$j['guards']);}else{$terminal['status']='failed';$terminal['errorCode']=in_array($body['errorCode']??'',['cli_failed','cli_timeout','invalid_output','invalid_budget','login_required'],true)?$body['errorCode']:'cli_failed';}$a['jobs'][$id]=$terminal;$reply(200,['accepted'=>true]);}
    if(preg_match('~^/jobs/([a-f0-9]{32})(/cancel)?$~',$path,$m)){$id=$m[1];$j=$a['jobs'][$id]??null;if(!$j)$reply(404,['error'=>'job_not_found']);if(!empty($m[2])&&$method==='POST'){$a['jobs'][$id]=['id'=>$id,'requestId'=>$j['requestId'],'hash'=>$j['hash'],'status'=>'cancelled','expires'=>$now+900];$reply(200,['cancelled'=>true]);}if($method==='GET'){if(!empty($j['requiresTeam'])||!empty($j['guards']['squad']))auth_require_permission($user,'team');if(!empty($j['requiresLeague'])||!empty($j['guards']['requiresLeague']))auth_require_permission($user,'league');}
if($method==='GET')$reply(200,['jobId'=>$id,'status'=>$j['status'],'snapshotHash'=>$j['hash'],'result'=>$j['result']??null,'errorCode'=>$j['errorCode']??null]);}
    $reply(404,['error'=>'route_not_found']);
}
